### ISSUE TITLE
1.4.4.1 flagged as Trojan:Win32/Azden.A!cl by Windows defender.

### ISSUE THREAD

**Issue by sharrken** [RevoLand/Steam-Library-Manager#10]
On downloading Steam Library Manager release 1.4.4.1, it is flagged as Trojan:Win32/Azden.A!cl by Windows Defender in Windows 10 (Insider Preview, Slow Ring, Current Release). This causes it to be automatically quarantined and deleted.

Defender details:
Threat Definition Version: 1.253.820.0
Version Created on: 12:12:04 : 16 October 2017
Antimalware Client Version: 4.12.16299.0
Engine Version: 1.1.14202.0
Antivirus Version: 1.253.820.0
Anti-spyware Version: 1.253.820.0
Network Realtime Inspection Engine Version: 2.1.14202.0
Network Realtime Inspection Signature Version : 118.0.0.0

OS Details:
Windows 10 Pro
Version 1709
OS Build 16299.15

**Comment by RevoLand** [comment]
Thank you for informing me about the situation. 
I've filled the submission form on Microsoft website and asked them to analyze it. You may follow the submission from [there](https://www.microsoft.com/en-us/wdsi/submission/575081ef-9586-42f2-92b9-b8575ec434c8), i will also keep you updated from here.

**Comment by RevoLand** [comment]
With Definition update 1.253.834.0, the issue is fixed for me. Can you please check and confirm that? Thanks in advance!
