### ISSUE TITLE
Not finding all steam library folders

### ISSUE THREAD

**Issue by PhnxZ** [RevoLand/Steam-Library-Manager#105]
I have 3 steam library folders:
C:\Games\Steam
E:\Games\Steam
G:\Games\Steam
Only the first 2 are shown in Steam Library Manager.

**Comment by RevoLand** [comment]
Should be fixed in [v1.7.1.0](https://github.com/RevoLand/Steam-Library-Manager/releases/tag/v1.7.1.0)

thanks!
