### ISSUE TITLE
Delete Files (with SLM) causes images to be unavailble

### ISSUE THREAD

**Issue by dewthefifth** [RevoLand/Steam-Library-Manager#12]
After choosing to remove a library entry using SLM, all of the library entries lose their images for varying amounts of time. I suspect this is caused by a latency in the grid view updating, but can't be certain.

To specifically reproduce the item:
This is my first time using SLM, and I'm actively moving and removing multiple entries, I've told a number of items to move from my primary library to a secondary library, and they're transferring in the Task Manager. However, as I come to entries I want to remove I'm right clicking and choosing "Delete Files (with SLM)" from the context menu.

**Comment by RevoLand** [comment]
Fixed on d4f7d36

**Comment by dewthefifth** [comment]
Thanks. I will.

I've been working using the pre-compiled exe instead of building. Is every commit built by a CI server, or are manual builds the only way to use a specific commit?

**Comment by RevoLand** [comment]
Currently there is no CI server integrations i have done so i am building manually via visual studio. Almost all of the commits should have the pre-compiled exe under /Binaries/ folder.

I wouldn't mind using a CI server or similar if that would be better, suggestions are always welcomed :)

**Comment by dewthefifth** [comment]
I've never done CI with github before, only had limited interaction with FOSS contributions. Professionally I use Java, and we compile using Bamboo, but I'm sure there has to be something similar (Jenkins) for github. I'm just not quite sure how to make it work with C#. 

I'll try to look into it and see if I can't find how to make something like Jenkins work with github and C#.
