### ISSUE TITLE
Delete using Task Manager (suggestion)

### ISSUE THREAD

**Issue by dewthefifth** [RevoLand/Steam-Library-Manager#13]
If deleting an item were queue'd in the task manager in the same way moving an item is, it might reduce system stress/lag and result in a cleaner experience.

You would of course need some sort of indicator on the library view to show the item is queue'd for deletion.

**Comment by RevoLand** [comment]
First of all thank you for your suggestion.

I've successfully implemented the requested feature in beta branch (commit 1f18eea) and it will be available in stable branch soon 👍
