### ISSUE TITLE
Settings changes are not persistent

### ISSUE THREAD

**Issue by scottpk** [RevoLand/Steam-Library-Manager#19]
Great utility, however I find that every time I open the app it is back to the default settings. Do I need to create a settings file or something before I can save the settings?

**Comment by RevoLand** [comment]
Thank you,

Whenever you run SLM, it is supposed to create a settings file called as "SLM.settings" which can be opened with any text editor. And any changes made in settings page should be saved automatically. 

To further investigate your issue, can you please check if it does generates a file called "SLM.settings" besides SLM binary?

Here is an example of "SLM.settings" file:
![16-tuesday-bf53e04e532](https://user-images.githubusercontent.com/2829482/34965669-e672ea26-fa66-11e7-9069-182e29548cd2.png)

**Comment by scottpk** [comment]
Apologies for the delayed response… No, I do not see the file even though I have checked the box to show hidden items in File Explorer.

Sent from Mail for Windows 10

**Comment by RevoLand** [comment]
No need for an apologies. I will be compiling SLM with an another settings provider to see if it is causing the error. 

Meanwhile, can you please confirm that running SLM under administrator privileges and trying to run SLM under another folder still doesn't generates a settings file?

Thank you :)

**Comment by scottpk** [comment]
Yes, thanks for the suggestion - it seems that the file gets generated when
it is in a sunflower even if it is not run as administrator, and the
settings get saved - it seems there is only an issue when the binary is
saved at the root of my D: drive...

**Comment by RevoLand** [comment]
Hello again,

I've fixed the mentioned bug and will be fixed in the next version.

Thank you again for reaching to me and letting me know about the issue.
