### ISSUE TITLE
Transfer speed over a 10Gig network caps out at 600mb/s

### ISSUE THREAD

**Issue by Inrixia** [RevoLand/Steam-Library-Manager#20]
I can use explorer to copy a steam folder from my SSD to my NAS at around 600MB/s or 4.8gb/s but whenever I try use SLM to move them it caps out at 600mb/s. This is copying to a network share.

**Comment by Inrixia** [comment]
Sweet, Ill test it when I get home if its been released :)

**Comment by RevoLand** [comment]
This should be only applies if you are compressing the game and i haven't seen you mentioned that. 

I can add an option to let you easily select compression method if needed for the next versions.

**Comment by Inrixia** [comment]
Right. I also just realized that my original message had a typo in it as the speed when using SLM is 600mb/s not MB/s

**Comment by Vykyan** [comment]
@RevoLand If you could add a Compression Level selector, that would be great!

**Comment by RevoLand** [comment]
@Vykyan 
Implemented with commit 985c4bb . Thank you for the suggestion!

@Inrixia 
Can you contact with me over Steam or Discord so we can test stuff like different buffer size or a different file movement method etc whenever you are free? Thanks.

**Comment by Vykyan** [comment]
@RevoLand Wow, thanks mate, so fast!

**Comment by Inrixia** [comment]
Idm the delay :) I'm currently away from home for two weeks though so I'll test it when I get back. Thanks for continuing to support this btw <3

**Comment by Inrixia** [comment]
Oh and I just realised I didn't get notified for your previous message to me so rip... I'd be happy to chat if that version doesn't work.
