### ISSUE TITLE
Support uPlay

### ISSUE THREAD

**Issue by Vykyan** [RevoLand/Steam-Library-Manager#23]
I love using Steam Library Manager, and adding Origin is awesome.  I'd really appreciate if you could look into supporting backing up uPlay games.  Cheers!

**Comment by RevoLand** [comment]
Thank you for using Steam Library Manager.

We still got a lot of things to do before calling out Origin support as completed. We need to find a more unified name at first. Also we are still missing header images for Origin games (Which is going to be implemented in a short time) and different manifest file versions other than 4.0, 2.1, 1.1 (if there is any)

But thank you for your feedback on that. I will try to speed up the things. 😄

**Comment by Vykyan** [comment]
Thanks for the reply, honestly, you don't need to rush!  Take your time mate and thanks for all your hard work! :)

**Comment by Vykyan** [comment]
Sorry closed by accident.

**Comment by RevoLand** [comment]
The support is here and will be live with the next release. Thanks!
