### ISSUE TITLE
Create a Release 

### ISSUE THREAD

**Issue by arranf** [RevoLand/Steam-Library-Manager#3]
Use the Github release feature to produce a download that doesn't contain the source code, to avoid storing binaries in source, and to help people who don't understand GitHub not have to process why there are .git files!

**Comment by RevoLand** [comment]
[Releases](https://github.com/RevoLand/Steam-Library-Manager/releases) already contains pre-compiled exe without extra files. I guess you mean there is /Bineries/ folder in 'master' branch. I am using the files in Binaries for auto-updater thing.

I may change the auto-updater function but need to finish converting SLM to wpf first. I am closing the issue, if you meant something else nor for anything please re-open the issue. Thanks!
