### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by Ethan-BB** [RevoLand/Steam-Library-Manager#31]
**Describe the bug**
Error on startup

System.FormatException: Input string was not in a correct format.
at System.Number.StringToNumber(String str, NumberStyles options,
parseDecimal)
at System.Number.ParseInt32(string s, NumberStyles style,
NumberFormatInfo info)
at System.Convert.ToInt32(String value)
at Steam_Library_Manager.Definitions.OriginLibrary.UpdateAppList()

**To Reproduce**
Start a program

**Expected behavior**
No error on startup

**Screenshots**
![image](https://user-images.githubusercontent.com/12885129/50649572-8d27c300-0f7e-11e9-934a-4729f19d729d.png)

**Additional context**
Program starts after the error, but I'm not sure how functional it is.
Also origin library is missing thumbnails:
![image](https://user-images.githubusercontent.com/12885129/50650220-24414a80-0f80-11e9-89c1-01ee068b91f3.png)

**Comment by RevoLand** [comment]
First of all thank you for reaching out to me on this issue. Missing header images for Origin games are known issue for now.

About the issue you are having, it is related to reading/parsing an Origin game. Would you please send me the "__Installer/installerdata.xml" files for each Origin game installed in the library? You can probably just search for the "installerdata.xml" at the root and i will handle the rest and find the missing/bugged manifest version parsing and correct it.

Thanks in advance!

**Comment by Ethan-BB** [comment]
Thank you for quick reply.
Here's all 10 installerdata XMLs found in my origin games folder.

https://drive.google.com/open?id=13DLuPB_76Z97Sz3JyngCKogAdLXOYqLe

**Comment by RevoLand** [comment]
Fixed in release [v1.5.0.15](https://github.com/RevoLand/Steam-Library-Manager/releases/tag/v1.5.0.15)

Please let me know if the issue persists or happens with a different game, thanks again for your help!
