### ISSUE TITLE
Compression with compact.exe

### ISSUE THREAD

**Issue by Chaython** [RevoLand/Steam-Library-Manager#34]
**Is your feature request related to a problem? Please describe.**
What compression does this client use? Applications need to be decompressed to play? Why not use a live decompression like windows compact.exe? I originally thought this software was basically compactGUI with steam integration, and automation.... https://github.com/ImminentFate/CompactGUI
**Describe the solution you'd like**
Integrate compact.exe as a compression method, like compactGUI does
This compression in most cases is not nearly as good; however it's much more useful as you can play your games still... I do realize that this tool is 100% focused on backups... But this feature would be great...

**Comment by RevoLand** [comment]
Hello!

I am using built-in [ZipFile](https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.zipfile?view=netframework-4.7.2) class for compression.

Yes, you are right. As the compression meant for/focused on backups, you must de-compress before playing.

Thanks for the suggestion, i will be implementing it in a near future!

**Comment by Chaython** [comment]
Was this ever implemented? / any progress?

**Comment by RevoLand** [comment]
Hello, this feature is still not implemented and not being worked on.

Sorry for the delay, i will be giving it a priority, expect it to be implemented soon.

**Comment by RevoLand** [comment]
Have a sneak peek into what's coming, suggestions are welcomed.


> ![](https://dl.dropboxusercontent.com/s/78e6gsa2hs358ha/17-Friday-cF43AA35968.png)
> ![](https://dl.dropboxusercontent.com/s/j6lfl5u1pe6ome0/17-Friday-Eg40xW32967.png)

**Comment by Chaython** [comment]
Looks good, I was expecting a merge/coding yourself 😋
________________________________

**Comment by RevoLand** [comment]
I've finally implemented the feature with abilities to:
- Compress (can be forced)
- Uncompress (can be forced)
- Get/show compact status

To task an app for compact compression you have to select "Compact" from context menu in library view. Please report any errors you do encounter with the feature as i am releasing it in beta state. Also do not hesitate to contact me for possible improvements can be done with compact feature nor Steam Library Manager.

Thanks again! Have a great day.

[Release v1.5.1.4](https://github.com/RevoLand/Steam-Library-Manager/releases/tag/v1.5.1.4)
