### ISSUE TITLE
No button to decompress a game after it was compressed.

### ISSUE THREAD

**Issue by thakyZ** [RevoLand/Steam-Library-Manager#41]
**Describe the bug**
Any game labeled as a compressed game doesn't have an decompress button, while all the uncompressed games have a decompress button

**To Reproduce**
1. Left click on a compressed game.
2. Left click on an uncompressed game.
3. See that there is no way to decompress a compressed game, without doing it manually.

**Expected behavior**
The compressed games should have a button to decompress the game

**Screenshots**
![image](https://user-images.githubusercontent.com/950594/56851983-17978800-68ca-11e9-8fbe-888320735320.png)
![image](https://user-images.githubusercontent.com/950594/56851993-30a03900-68ca-11e9-8f04-6564695f0201.png)

**Comment by RevoLand** [comment]
Issue should be fixed now. Thank you for reporting :)
