### ISSUE TITLE
Cant select Target for Compressing

### ISSUE THREAD

**Issue by h1ght** [RevoLand/Steam-Library-Manager#42]
Hello,

just looked how i can backup steamgames inclusive their workshop content.
even with 100mbits its a pain to download alot. 

i try to backup them, but i cant select or configure the target directory for backups. 

regards

**Comment by RevoLand** [comment]
Hello,

To backup games you have to create a new SLM library to use for backups.
Alternatively you can create Steam library to move games between drives.

Please use our Discord server for similar questions and keep the GitHub for issues/bugs/requests.
Thank you for using SLM :)
