### ISSUE TITLE
Task Manager doesn't show a percentage for Compact

### ISSUE THREAD

**Issue by Chaython** [RevoLand/Steam-Library-Manager#43]
**Describe the bug**
Hey again; thanks for adding compact.  There's this bug however: Task Manager doesn't show a percentage for Compact. At least I assume the percentage on the right is for completion of the task?

Once again I would like to recommend this transparent compression over any other.
Absolver 14.1gb = 8.45gb

**Comment by RevoLand** [comment]
Hello, thanks to you for using SLM! :)

Sorry for my laziness. I've fully implemented the compact function now and it should report progress & compact all files (including workshop files etc).

I will be releasing a new version in a few hours, will be making a few controls first. Thank you for the report.
