### ISSUE TITLE
SLM finds an update of the  current version upon manual check

### ISSUE THREAD

**Issue by Chaython** [RevoLand/Steam-Library-Manager#44]
**Describe the bug**
SLM finds an update of the current version upon manual check

**To Reproduce**
1. Go to 'settings'
2. Click on 'check for updates'
3. See error

**Expected behavior**
It should not offer to download a newer version when there isn't one
**Screenshots**

![image](https://user-images.githubusercontent.com/6486343/58432608-79394680-8070-11e9-855f-20ac2eada398.png)

**Comment by RevoLand** [comment]
Thank you for your report, it should be fixed on the next release.
