### ISSUE TITLE
Compacted File Size

### ISSUE THREAD

**Issue by Chaython** [RevoLand/Steam-Library-Manager#46]
**Describe the bug**
A compacted game will report that it's compacted, and in the taskmanager it shows you the compact size, compression ratio etc of each file. However if you go back to the library it reports the size not the size on disk.
Also in the previous build upon task completion it logged a summary on the last line, stating the original - compact, and ratio. Not sure why I recall that yesterday but it's missing in this build.

**Expected behavior**
If a game is compacted show:
Compacted
Size on Disk (Size)
**Screenshots**
![image](https://user-images.githubusercontent.com/6486343/58476460-0bdbf300-810e-11e9-8763-ed5c686ae470.png)

Thanks as always <3

**Comment by RevoLand** [comment]
There is a huge performance penalty coming from determining the compacted folder size (especially on games with lots of subfolders) as i couldn't find any other methods available to get the size on disk (including invoke methods).

However i will be keeping the implementation with an option to enable/disable (disabled by default) to determine or not determine the compacted folder size.

![](https://dl.dropboxusercontent.com/s/6auoku4tvtlstov/28-Tuesday-G480dg6R986.png?123)

**Comment by Chaython** [comment]
Not sure what performance issues you're referring to?
My CPU usage during compact is <4% 1.5% avg.
As stated the previous build logged disk size on completion
![image](https://user-images.githubusercontent.com/6486343/58510496-18843980-8156-11e9-8824-ae9fe94a86a1.png)

**Comment by Chaython** [comment]
The new build says compression / file rather than on completion
![image](https://user-images.githubusercontent.com/6486343/58510649-6dc04b00-8156-11e9-8a51-c8a52a8deb9c.png)
Could show size on completion as before then query that into the compact/ size somehow?
I'm an idiot and can't help you, and you're doing great work! Thanks as always <3

**Comment by RevoLand** [comment]
Give a try to [this unreleased version](https://send.firefox.com/download/eb69369d6e4900cc/#WtoAdz_N3NbbzFQ9t10PUg), activate the Advanced Compact Size Detection and restart SLM. You will see what i mean by the performance issue (getting & showing compact'ed size on library view)

Logging per file can be disabled by unchecking the "Report File Movement" option.

**Comment by Chaython** [comment]
This build seems to take longer to scan the installed apps, I assume is what you mean?

**Comment by RevoLand** [comment]
> 
> 
> This build seems to take longer to scan the installed apps, I assume is what you mean?

Exactly, but it gets the correct size for each compact'ed game.

**Comment by Chaython** [comment]
IDK, the performance hit shouldn't be so heavy.
Time of completion - SLM clean install - 8.5 seconds ; advanced compact - 4 minutes
It's like it's individually checking every file rather than just the directories 
It's also only using <50kb/s ~20kb/s <1% cpu

**Comment by RevoLand** [comment]
> 
> 
> IDK, the performance hit shouldn't be so heavy.
> Time of completion - SLM clean install - 8.5 seconds ; advanced compact - 4 minutes
> It's like it's individually checking every file rather than just the directories
> It's also only using <50kb/s ~20kb/s <1% cpu

That's because we have to run "compact /s /q" on each game installation to get a proper size, which hits the performance on games with lots of subfolders.

You may keep the "Advanced Compact Size Detection" disabled which only effects the game size in library view.

**Comment by Chaython** [comment]
Can't you just reference window's indexing somehow?

**Comment by RevoLand** [comment]
> 
> 
> Can't you just reference window's indexing somehow?

I wish i could but as i said earlier i couldn't find any method (including invoking windows) to get the size unfortunately.

**Comment by Chaython** [comment]
Could try PS
This is used to get size of files on disk, doesn't show directory/subdir size though; but maybe you'll know how to get dir size after seeing this :/
https://www.opentechguides.com/how-to/article/powershell/133/size-on-disk-ps.html

**Comment by RevoLand** [comment]
I am aware of "GetCompressedFileSizeW" but since it only gets for a single file, it would suffer much more than running the compact command. Appreciated for the research :)

**Comment by RevoLand** [comment]
[v1.5.1.6](https://github.com/RevoLand/Steam-Library-Manager/releases/tag/v1.5.1.6) is released now.
