### ISSUE TITLE
Save Manager

### ISSUE THREAD

**Issue by Chaython** [RevoLand/Steam-Library-Manager#48]
https://github.com/MikeMaximus/gbm
Would be nice to integrate a save game manager ...
Yes, I know I'm annoying but it seems you're really dedicated :P <3

**Comment by RevoLand** [comment]
I love the idea but that is outside the scope of SLM. Programs such as [Game Save Manager](https://www.gamesave-manager.com/) already do it so well, there's no reason to reinvent the wheel.
