### ISSUE TITLE
Library Meta Info Truncated on Left

### ISSUE THREAD

**Issue by arranf** [RevoLand/Steam-Library-Manager#5]
![image](https://cloud.githubusercontent.com/assets/8703222/12869256/f441c4bc-cd11-11e5-9a00-38112a526bae.png)

You can see that the number of games following the path on the left library is truncated.

**Comment by RevoLand** [comment]
With wpf this won't be a issue and i am getting very close to end on wpf app, will apply a temporary fix with symlinks.

**Comment by RevoLand** [comment]
Fixed in 99d4e85
