### ISSUE TITLE
1.5.1.6 (De)Compressing: The given key was not present in the dictionary

### ISSUE THREAD

**Issue by shakeyourbunny** [RevoLand/Steam-Library-Manager#50]
**Describe the bug**
If I try to (De)compress a game, it cancels with the error message "The given key was not present in the dictionary".

**To Reproduce**
1. Right-click on any game.
2. Select "(de)compress"
3. (optionally) Start Task manager

**Expected behavior**
Compressing the game, as advertised.

**Additional context**
Added compressed logfile.

[2019-05-31.zip](https://github.com/RevoLand/Steam-Library-Manager/files/3240953/2019-05-31.zip)

**Comment by RevoLand** [comment]
Thank you for your error report, i was able to find 2 more minor issues with this one and will be releasing a new version now.

- 'The given key was not present in the dictionary' on compress tasks. (Issue: #50)
- Task Manager UI for compression related tasks.
- Can't task an item for compact if the item is already tasked for compression (and vice-versa)
