### ISSUE TITLE
Compression / Archiving

### ISSUE THREAD

**Issue by shakeyourbunny** [RevoLand/Steam-Library-Manager#52]
**Is your feature request related to a problem? Please describe.**
Quality of Life user interface improvement.

**Describe the solution you'd like**
It would be neat to see on compressed games, how much space you have saved (toggleable perhaps by percent / how much saved / original game size)?

Add to the task manager button "check for backup updates" a configurable option these options:
- update game in library / zip (needs rebuild of archive zip for the latter) (default)
- put changed stuff in new folder "appid-YYYYMMDD" (or zip) alongside with an batchfile for removing removed files.

**Additional context**
Possible some UI setting for setting the ZIP compression level (6 is default, 9 is max or so).

edit: would be cool, if you would also put the workshop items in the ZIP or in a APPID-workshop.zip ;-) Thanks!

**Comment by shakeyourbunny** [comment]
would be really neat, if you could such delta updates :D

**Comment by RevoLand** [comment]
> 
> 
> would be really neat, if you could such delta updates :D

Delta updates? Like; "appid-<date>.zip" for each update, rather than regenerating the file? What is on your mind? :)

>
>
> edit: would be cool, if you would also put the workshop items in the ZIP or in a APPID-workshop.zip ;-) Thanks!

Separate game files by common, downloading and workshop? Would that get agreed by everyone? I mean... extra archive files for each game 😄 

Also it would be great to have some ideas about improving the layout of SLM like app view, library view, task manager etc. At the moment, we are pretty low on free space to put extra stuff like compression level / format stuff to task manager.

Thank you again for your ideas, I will be reviewing active "issues" and informing you.

**Comment by shakeyourbunny** [comment]
>Delta updates? Like; "appid-.zip" for each update, rather than regenerating the file?
> What is on your mind? :)

Yes and no, but at least it would be nice to have the appid-YYYYMMDD.zip for the indiviual versions of the game, in order to have older versions.

Another step would be having optional delta updates just zip all changed files (and a autogenerated batch to remove removed directories and files).

I wrote a simple directory comparer in Python3 and compared the current Grim Dawn game with the version of the backup, here is the output:

```
F-  common\Grim Dawn\GDMapStitch_x64_v2.zip
MD5 appmanifest_219990.acf
MD5 common\Grim Dawn\AifEditor.exe
MD5 common\Grim Dawn\AnimationCompiler.exe
MD5 common\Grim Dawn\ArchiveTool.exe
MD5 common\Grim Dawn\AssetManager.exe
MD5 common\Grim Dawn\BitmapCreator.exe
MD5 common\Grim Dawn\Direct3D.dll
MD5 common\Grim Dawn\Direct3D11.dll
MD5 common\Grim Dawn\DirectInput.dll
MD5 common\Grim Dawn\DS8Sound.dll
MD5 common\Grim Dawn\Editor.exe
MD5 common\Grim Dawn\Engine.dll
MD5 common\Grim Dawn\Game.dll
MD5 common\Grim Dawn\Grim Dawn.exe
MD5 common\Grim Dawn\MapCompiler.exe
MD5 common\Grim Dawn\MaxPlugins2009.dlo
MD5 common\Grim Dawn\MaxPlugins2011.dlo
MD5 common\Grim Dawn\MaxPlugins2012.dlo
MD5 common\Grim Dawn\ModelCompiler.exe
MD5 common\Grim Dawn\PSEditor.exe
MD5 common\Grim Dawn\ShaderCompiler.exe
MD5 common\Grim Dawn\SourceControl.dll
MD5 common\Grim Dawn\SourceServer.exe
MD5 common\Grim Dawn\TextureCompiler.exe
MD5 common\Grim Dawn\Viewer.exe
MD5 common\Grim Dawn\Widget.dll
MD5 common\Grim Dawn\database\database.arz
MD5 common\Grim Dawn\database\templates.arc
MD5 common\Grim Dawn\resources\Conversations.arc
MD5 common\Grim Dawn\resources\Creatures.arc
MD5 common\Grim Dawn\resources\Fonts.arc
MD5 common\Grim Dawn\resources\FX.arc
MD5 common\Grim Dawn\resources\Items.arc
MD5 common\Grim Dawn\resources\Level Art.arc
MD5 common\Grim Dawn\resources\Levels.arc
MD5 common\Grim Dawn\resources\Shaders.arc
MD5 common\Grim Dawn\resources\System.arc
MD5 common\Grim Dawn\resources\Text_EN.arc
MD5 common\Grim Dawn\resources\UI.arc
MD5 common\Grim Dawn\x64\Direct3D.dll
MD5 common\Grim Dawn\x64\Direct3D11.dll
MD5 common\Grim Dawn\x64\DirectInput.dll
MD5 common\Grim Dawn\x64\DS8Sound.dll
MD5 common\Grim Dawn\x64\Engine.dll
MD5 common\Grim Dawn\x64\Game.dll
MD5 common\Grim Dawn\x64\Grim Dawn.exe

Old size: 4020308.1 KB, New size: 4046556.7, Changed Files: 2226264.9 KB
```

Both game versions have about 4 GB uncompressed data and the changed files only have about 2 GB (mostly due to the container files and not single files).

If you would do xdelta3 on the changed files, the 2 GB would shrink tremendously, but creating a proper patching routine would be tricky, I guess.

**Comment by shakeyourbunny** [comment]
Addendum, I added automatically zipping the changed files (without cleanup script), this yielded an archive size of about 1,8GB (iinstead of the 2 GB loose files).

**Comment by Dimensional** [comment]
One suggestion to include for the UI, since it was brought up earlier, is to shrink either the log space or the interface space a little, to include a section for changing the settings for all games being moved/copied/compressed. Should speed up the process if you're planning on having all the games go through the same procedure, and then you could deselect the few that aren't going to have identical options, like getting compressed while backing up into the SLM folder.
