### ISSUE TITLE
Open / Close / Refresh Library / Logo

### ISSUE THREAD

**Issue by shakeyourbunny** [RevoLand/Steam-Library-Manager#53]
**Is your feature request related to a problem? Please describe.**
No, just an improvement for the Library screen.

**Describe the solution you'd like**
**Open Library**: open / add an existing SLM library
**Close Library**: removes an existing SLM / Steam / Uplay library from SLM
**Refresh Library**: refresh contents of SLM / Steam / Uplay library.

Latter is practical if you do something behind the back of SLM and do a (manual) refresh to reread the contents of the library.

**Logo**: put a distinctive logo for each type of library (Steam / SLM / Uplay)

**Describe alternatives you've considered**

**Additional context**
You can arrange these buttons at the bottom left of the window. Perhaps replace the current "Create Library" with a button row (with tooltips):

"Create Library" "Open Library" "Close Library" "Refresh Library"
"+" "📂" "📁" "⟲"
"+" "unicode: U+1F4C2" "unicode: U+1F4C1" "unicode: U+27F2"

**Comment by RevoLand** [comment]
Hello,

I've implemented as this:
![](https://dl.dropboxusercontent.com/s/a6xevt3su0f9emb/02-Sunday-p727uP1P990.png)

I haven't added a button for opening a SLM library since creating/opening a SLM library is basically same thing.

Please let me know if this can be improved further. Thank you for the suggestion.

**Comment by shakeyourbunny** [comment]
I thing this looks good ;-))

**Comment by RevoLand** [comment]
Let's keep the issue open as the logo part is not implemented yet. :)

**Comment by RevoLand** [comment]
![](https://dl.dropboxusercontent.com/s/vg31cl4aruf7rd1/09-Sunday-3X44mH5h993.png)

Done! :)
