### ISSUE TITLE
More UI improvements

### ISSUE THREAD

**Issue by shakeyourbunny** [RevoLand/Steam-Library-Manager#54]
**Is your feature request related to a problem? Please describe.**
I'm sorry, if I spam you with requests, but I have so much ideas for this application.
Just suggestions for UI improvements.

**Describe the solution you'd like**
*Readability of game list*
- have some grid in the list, sometimes hard to read or to keep in the line 
- list view: first line white, second line darker for better readability

*tooltips*
Please add tooltips what what button or radio switch does exactly. I reread your documentation two or three times and I am still not sure what some things do.

*task manager autoclean jobs*
Add a radio button for autocleaning jobs, when they are finished.

*library cleaner: reason why junk*
- add a grid to the list for better readability
- Add a column why SLM thinks an entry is junk 
- add a radio button to ignore stuff which are both present in SLM and Steam/other library (this is not junk)

**Comment by RevoLand** [comment]
Please don't be sorry at all!

Bug reports or feature requests are makes me happy more than ever. This is actually the only way to get SLM better for everyone.

I have been thinking about re-writing SLM from scratch on [Electron](https://electronjs.org/) for a while, which would probably get rid of the every issue related to design/ui or WPF based limits with the power of html, css and js.

I will be implementing the improvements you have suggested in the next version, thank you and please keep it coming :)

**Comment by shakeyourbunny** [comment]
Please not yet another Electron App.....  why do you don't want to stick to standard UI toolkit? Does C# not have one?

If you do something from https://www.mono-project.com/docs/gui/ (Win.Forms for example), there is the possibility to do an easy port to Linux with Mono if the need arises if you want to stay with C#. 

I also dislike WPF, but Electron is a worse choice, especially you just have a browser in a frame without navigation elements and you have to code every UI element by hand. 

Myself I do some Python, but currently only console stuff, because I want to learn the language better before doing GUI stuff, but then I'd use PyQT.

**Comment by RevoLand** [comment]
Here is the sum of progress we have made.
- [x] Tooltips
- [x] Ability to auto clear completed tasks
- [x] Ability to ignore library cleaner items
- [x] Library Cleaner: Reason why junk
- [ ] Library Cleaner: Grid View (?)
- [ ] App Panel: Grid View UI Update
- [ ] App Panel: List View UI Update

**Comment by RevoLand** [comment]
> 
> 
> Please not yet another Electron App..... why do you don't want to stick to standard UI toolkit? Does C# not have one?
> 
> If you do something from https://www.mono-project.com/docs/gui/ (Win.Forms for example), there is the possibility to do an easy port to Linux with Mono if the need arises if you want to stay with C#.
> 
> I also dislike WPF, but Electron is a worse choice, especially you just have a browser in a frame without navigation elements and you have to code every UI element by hand. In addition, if you don't have a more recent computer, this is slower than WPF.
> 
> Myself I do some Python, but currently only console stuff, because I want to learn the language better before doing GUI stuff, but then I'd use PyQT.

I have a few arguments to use Electron (actually to use html/css/js). UI and analytics (definitely anonymous, can be opted out, only to be used by me or publicly)

About the UI, i have properly used the accents and buttons of mahapps with the latest update and unified most of the ui stuff so that is not a big problem as it is used to be.

With the node.js stuff, we could even serve on local ip and show task status or some statistics to be accessed from LAN. It probably can be done with c# too but it doesn't sounds interesting as node.js does lol. Also lack of interest on SLM makes things get slower.

**Comment by RevoLand** [comment]
Here is the re-worked UI for Library Cleaner tab. With this changes; Ignoring items will also work properly.

![](https://dl.dropboxusercontent.com/s/769vfvitookxoxo/04-Sunday-pY72SE8R1035.png)

> _HeadlessFolder will be replaced with translation text_

Please let me know if this can be improved.

**Comment by shakeyourbunny** [comment]
BTW the whole Win10isms of the interface and the forced "do you want to (re)start Steam" (without the checkbox) is really making this application nearly unusable.

I'm really tempted to make my own version from scratch with a proper standard user interface and not with this pseudo html interface.

**Comment by RevoLand** [comment]
> 
> 
> BTW the whole Win10isms of the interface and the forced "do you want to (re)start Steam" (without the checkbox) is really making this application nearly unusable (as of 1.6.0.3).
> 
> I'm really tempted to make my own version from scratch with a proper standard user interface and not with this pseudo html interface. Oh and there is really no possibility to navigate through the application if you don't have a mouse...

Well we have been using mahapps for a long time and it is integrated in half of SLM's code. (You may take a look at a0d10f5)

As you have noticed changing the UI requires a lot of work to do rather than simply reference removal. Plus we would be missing some stuff like Hamburger menu, Flyout panel that we are using for library creation etc.

At this current state i believe it is redundant to remove mahapps, doesn't worth the all hassle that it requires. Thank you.
