### ISSUE TITLE
Support for more library types

### ISSUE THREAD

**Issue by RevoLand** [RevoLand/Steam-Library-Manager#65]
- [x] Uplay (#23 #71)
- [ ] Epic Games Launcher (#92)

**Comment by RevoLand** [comment]
Won't do epic games until i find a way for getting header images.

**Comment by NelsonMinar** [comment]
If you can make a general purpose game library manager, that'd be amazing. As the different launchers proliferate it's getting to be a real pain to figure out each one on my own.

PC Gamer had a good article recently on manually copying games around about two months ago. It includes detailed instructions for about seven launchers including all the quirks to fake them out. Maybe not so detailed as how to get header images, but it's a good reference for the basics.

The article is at https://www.pcgamer.com/how-to-transfer-game-files-between-pcs/

**Comment by RevoLand** [comment]
> 
> 
> If you can make a general purpose game library manager, that'd be amazing. As the different launchers proliferate it's getting to be a real pain to figure out each one on my own.
> 
> PC Gamer had a good article recently on manually copying games around about two months ago. It includes detailed instructions for about seven launchers including all the quirks to fake them out. Maybe not so detailed as how to get header images, but it's a good reference for the basics.
> 
> The article is at https://www.pcgamer.com/how-to-transfer-game-files-between-pcs/

Thank you for the interest, but what you are suggesting is beyond the scope of SLM. From that article, many of those suggestions, such as Windows Store and GOG, will not work due to game-specific system requirements like registry entries and folder permissions. SLM is meant as a way to move games around on your computer, or back them up to other media such as an external hard drive.

We are not against Implementing more clients into SLM, so feel free to post suggestions on which to support next.

**Comment by shakeyourbunny** [comment]
Would be neat to be able to backup your GOG Galaxy game installations though.
