### ISSUE TITLE
Disk Space with Mounted Volumes

### ISSUE THREAD

**Issue by habilain** [RevoLand/Steam-Library-Manager#72]
This is kind of obscure; if a disk is mounted as a directory in a filesystem, then the free space indicator for a steam library on that disk will show the parent filesystem rather than the correct filesystem.

**To Reproduce**
1. Mount a disk as a directory (see: https://docs.microsoft.com/en-us/windows-server/storage/disk-management/assign-a-mount-point-folder-path-to-a-drive), e.g. C:\Media\Disk1
2. Place a Steam Library on that disk e.g. C:\Media\Disk1\SteamLibrary
3. Open Steam Library Manager
4. The disk usage indicator for the steam library on the directory mounted disk will show the disk stats of the root disk, C:\

**Expected behavior**
The disk usage indicator should use the stats of the mounted disk i.e. C:\Media\Disk1

I'm afraid I'm normally a Python dev, so I can't help out with this directly. In Python you would simply use shutil.disk_usage on the Steam Library path and it behaves correctly, so I assume that fixing this will be finding an equivalent C# function.

**Comment by RevoLand** [comment]
Thank you for issue reporting, i will be reproducing and fixing the issue however it may take a bit until next release gets published as i am planning to release the next version as 1.6; with Uplay support.

**Comment by RevoLand** [comment]
I have fixed the issue and the fix will be live on the next release. 

*C:\SLMTest\Oyunlar\SLMTest (SLM)* is a mounted volume.
![](https://dl.dropboxusercontent.com/s/yw1b68ubkq7y9ir/31-Wednesday-Zn448Q6B1028.png)
