### ISSUE TITLE
Duplicate Finder/Cleaner

### ISSUE THREAD

**Issue by mmorselli** [RevoLand/Steam-Library-Manager#73]
If you copy a game from one library to another forgetting to check "remove original files" you end up with two identical copies of the game.

Since each copy has its own .acf the library cleaner does not detect it, and it can be a huge waste of space

It would be useful if the library cleaner also recognized these cases, checking .acf of the same game and showing size and location of the corresponding folders

**Comment by RevoLand** [comment]
Thank you for the suggestion. I've implemented it and it will be live on the next release!

Have a sneak-peek:
![](https://dl.dropboxusercontent.com/s/3hz9ouq5ef91qb6/02-Friday-bQ05Fe2M1032.gif)
