### ISSUE TITLE
Out of Range Exception upon launch

### ISSUE THREAD

**Issue by rbuskirk** [RevoLand/Steam-Library-Manager#8]
When I launch the application I get and exception (see attached screenshot). If I press "OK" SLM will continue to load except only my first (default) library will be shown in the left column.

<img width="349" alt="slm_exception" src="https://cloud.githubusercontent.com/assets/192016/21343899/08cd083e-c667-11e6-84c7-3bf19f70a620.png">

OS: Windows 10
SLM: v1.3.3 (Your binary)
Steam: Up-to-date
I have two libraries configured each on a different drive.

**Comment by RevoLand** [comment]
Can you please upload your .ACF files so i can test if it is caused from them or SLM? Thanks in advance!

**Comment by RevoLand** [comment]
Fixed in 5d6b8eced13ab9e5b30497063ad6ee097040426e
