### ISSUE TITLE
The specified executable is not a valid application for this OS platform

### ISSUE THREAD

**Issue by Makishima** [RevoLand/Steam-Library-Manager#88]
win10 x64
Hello! After I hit the update button from 1.5.1.3 and the update is downloaded and extracted I got this error
`The specified executable is not a valid application for this OS platform`
[ZipExtractor.log](https://github.com/RevoLand/Steam-Library-Manager/files/5401124/ZipExtractor.log)

And .exe is saying same 
![изображение](https://user-images.githubusercontent.com/5548003/96438866-41a3df00-120f-11eb-84d8-f664001d5b44.png)

**Comment by RevoLand** [comment]
Hello there,

Is it possible that your AV software detects Steam Library Manager executable as malicious? Archive might be corrupt as well.

I will be updating the dependencies soon and might consider changing the auto-updater if this issue persists.

Thanks for reporting!

**Comment by Makishima** [comment]
Not sure that AV is a problem. I can luach manager froim inside standalone downloaded .zip

**Comment by Makishima** [comment]
I check it with disabled AV and there is the same problem.

**Comment by shadow7412** [comment]
I just had it too - it's a 0 byte exe.

**Comment by RevoLand** [comment]
Thank you all for reporting the issue, i was able to reproduce the issue and it is fixed now. 🙏
