### ISSUE TITLE
Epic game support , Translation option is not available

### ISSUE THREAD

**Issue by Louisstree** [RevoLand/Steam-Library-Manager#92]
I am looking forward to supporting Epic game.

I want to help the software translate. But when I click Translate, it prompts that the resource does not exist.

Thank you .

**Comment by babusgap** [comment]
@Louisstree Epic ve Xbox kütüphanelerine bu desteğin gelmesi gerekiyordu teşekkür ederim fakat programın tekrardan derlenip sorunların çözülmesi gerekiyor playnite ekibi ile birleşmenizi daha verimli olucağını düşünüyorum yada diğer oyun kütüphanelerindeki oyunları steam kütüphanesinin içine sıralayacak aktarıcak bir sistemde düşünülebilir gog galaxy gibi bir programla birleşmeniz daha mantıklı olur
